
<form action="addArtist" method="POST">
   <input type="hidden" name="artist_id" value="<?= htmlspecialchars($artist->artist_id);?>">
    <div>
        <label for="artist_name">Artist name</label>
        <input type="text" id="artist_name" name="artist_name" value="<?= $artist->artist_name; ?>" required>
    </div>
    <div>
        <label for="artist_img">Artist image</label>
        <input type="text" id="artist_img" name="artist_img" value="<?= $artist->artist_img; ?>" required>
    </div>
    <div>
        <button type="submit">Add Artist</button>
    </div>

</form>
