<form action="add-song" method="POST" class="my-form">
    <select name="artist" required>
        <option value=""></option>
        <?php foreach ($artistList as $artist): ?>
            <option value="<?= $artist->artist_id ?>"><?= $artist->artist_name ?></option>
        <?php endforeach ?>
    </select>
    <input type="text" name="s_name" placeholder="Name" required>
    <input type="text" name="s_genre" placeholder="Genre" required>
    <input type="text" name="s_year" placeholder="Year" pattern="\d{4}" required>
    <div id="action-btns-container">
        <input type="submit" value="Add">
        <a href="view-songs"><input type="button" value="Cancel"></a>
    </div>
</form>

