<?= require './templates/header.phtml';?>
<form action="<?=BASE_URL?>update-artist" method="POST">
    <div>
        <input type="hidden" name="artist_id" value="<?= htmlspecialchars($artist->artist_id); ?>">
        <label for="artist_name">Artist name</label>
        <input type="text" id="artist_name" name="artist_name" value="<?= htmlspecialchars($artist->artist_name); ?>" required>
        <label for="artist_img">Artist image</label>
        <input type="text" id="artist_img" name="artist_img" value="<?= htmlspecialchars($artist->artist_img); ?>" required>
    </div>
    <div>
        <button type="submit">Actualizar Artista</button>
    </div>
</form>