<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

<form action="edit-song/<?=$song->song_id?>" method="POST">
    Name: <input type="text" name="s_name" value="<?= $song->song_name ?>" required>
    Genre: <input type="text" name="s_genre" value="<?= $song->song_genre ?>" required>
    Year: <input type="text" name="s_year" value="<?= $song->song_year ?>" pattern="\d{4}" required>
    <input type="submit" value="Save">
</form>