<?php require './templates/header.phtml';?>
<?php if (is_object($artist)): ?>
<form action="edit-artist/<?=$artist->artist_id?>" method="POST">
    
    <div>
        <label for="artist_name">Artist name</label>
        <input type="text" id="artist_name" name="artist_name" value="<?= htmlspecialchars($artist->artist_name); ?>" required>
        <label for="artist_img">Artist image</label>
        <input type="text" id="artist_img" name="artist_img" value="<?= htmlspecialchars($artist->artist_img); ?>" required>
    </div>
    <div>
        <button type="submit">Update artist</button>
    </div>
</form>
<?php endif ?>