<form action="edit-song/<?=$song->song_id?>" method="POST" class="my-form">
    Name: <input type="text" name="s_name" value="<?= $song->song_name ?>" required>
    Genre: <input type="text" name="s_genre" value="<?= $song->song_genre ?>" required>
    Year: <input type="text" name="s_year" value="<?= $song->song_year ?>" pattern="\d{4}" required>
    <input type="submit" value="Save">
</form>