<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
    <base href="router">
</head>
<body>
    <nav class="menu">
        <ul>
            <li><a href="home">Home</a></li>
            <li><a href="view-songs">My songs</a></li>
            <li><a href="view-artists">My artists</a></li> 
        </ul>
    </nav>
</body>
</html>
