<?php if (is_object($song) && is_object($artist)): ?>   
        <div id="song-details">
            <p><span class="category">Artist:</span> <?= $artist->artist_name ?></p>
            <p><span class="category">Name:</span> <?= $song->song_name ?></p>
            <p><span class="category">Genre:</span> <?= $song->song_genre ?></p>
            <p><span class="category">Year:</span> <?= $song->song_year ?></p>
        </div>
        <?php if (isLogged()): ?>
        <div id="details-btns-container">
            <a href="edit-song/<?=$song->song_id?>"><button>Edit</button></a>
            <a href="view-songs"><button>Back</button></a>   
        </div>         
        <?php endif ?>
<?php endif ?>

