<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php require 'templates/header.phtml' ?>
    <h2>Your artists</h2>
    <ul> 
    <?php foreach($artistList as $a): ?>
        <li> <a href= "view-artist/<?=$a->artist_name?>"> <?php echo $a->artist_name ?> </a> </li>
        <?php endforeach ?>
    </ul>
</body>
</html>