<h1>Your songs</h1>
<ul id="songlist">
    <?php foreach ($songList as $s): ?>
        <li><a href="view-song/<?=$s->song_id?>"> <?php echo $s->song_name ?> </a></li>
        
        <?php if (isLogged()): //si el usuario esta logueado muestra el boton?>
            <a href="delete-song/<?= $s->song_id ?>"><input type="button" value="Delete"></a> 
        <?php endif ?>
    <?php endforeach ?>
</ul>

<?php if (isLogged()):?>
    <div id="songlist-btns-container">    
        <a href="add-song"><input type="button" value="New Song"></a>
    </div>
<?php endif ?>