<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <?php require 'templates/header.phtml' ?>
    <?php if (is_object($song)): ?>
        <div id="song-details">
            <p>Name: <?= $song->song_name ?></p>
            <p>Genre: <?= $song->song_genre ?></p>
            <p>Year: <?= $song->song_year ?></p>
        </div>
    <?php endif ?>
</body>
</html>