<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <?php require 'templates/header.phtml' ?>
    <div id="song-details">
        <span>Name: <?= $song->song_name ?></span><br> <!-- sacar br-->
        <span>Genre: <?= $song->song_genre ?></span><br>
        <span>Year: <?= $song->song_year ?></span><br>
    </div>
</body>
</html>