<?php require './templates/header.phtml'?>
<h2>Your artists</h2>
<ul>
    <?php foreach ($artists as $a): ?>
        <li> 
            <a href="view-artist/<?= $a->artist_id ?>"> <?php echo $a->artist_name ?> </a> 
        </li>

            <form action="delete-artist/<?= $a->artist_id ?>" method="POST">
                <button type="submit">Delete</button></a> 
            </form>

    <?php endforeach ?>

    <div>
        <a href="add-artist/"><button>New Artist</button></a>
    </div>
    
    <!--<form action="add-artist" method="POST">
    <h2 >Add new artist</h2>
        <div>
            <label for="artist_name">Artist name</label>
            <input id="artist_name" type="text" name="artist_name" required>
            <label for="artist_img">Artist image</label>
            <input id="artist_img" type="text" name="artist_img" required>
        </div>
        <button type="submit">Add artist</button>
</form>
</ul>-->
